### ISSUE TITLE
Problem with cookies in Version 3.5

### ISSUE THREAD

**Issue by taphil** [wiztools/rest-client#37] opened 2015-05-19 09:16 UTC
In version 3.5 the cookies set in request seem to not be transferred sometimes
In the below screenshot I compared versions 3.3.1 (where it worked fine) and 3.5 (where it failed) with the exact same requests.
Please also find a screenshot of the used java version below

![2015-05-19 11-13-53_new issue wiztools_rest-client](https://cloud.githubusercontent.com/assets/9952850/7699486/7ed1178c-fe18-11e4-85c6-926d833dd6b5.png)
![2015-05-19 11-12-48_administrator_ c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/9952850/7699488/80b27758-fe18-11e4-85a6-0fb4b89ecf54.png)

**Comment by subwiz** [comment] 2015-05-19 09:18
Thanks for reporting. Will look into this today evening.

**Comment by subwiz** [comment] 2015-05-22 05:17
I tried manually, was not able to reproduce. My steps:

1. Menu > Tools > Start Trace Server.
2. Menu > Tools > Insert Trace Server URL.
3. Execute the request.
4. Verify the Response Body, you should see the Cookie being sent.

Can you check if this is caused by some other issue?

**Comment by taphil** [comment] 2015-05-22 06:37
that's interesting - as I didn't know the trace server tool, I just tried it and got the following outcome

Version 3.3.1 (works):
**RESTClient TraceServlet**

*Method*
	POST

*Path Info*
	/

*Headers*
	Accept-Encoding: gzip,deflate
	User-Agent: Apache-HttpClient/4.3.3 (java 1.5)
	Cookie: $Version=1; sessionId="9a4da3a2-3409-4883-9702-2653a13b25fa"
	Cookie2: $Version=1
	Connection: keep-alive
	Host: localhost:10101
	Content-Type: application/json; charset=UTF-8
	Content-Length: 691

*Query String*
	null

*Parameters*

*Body (First 100 characters only)*
	
Version 3.5 (set cookie - does NOT work):
**RESTClient TraceServlet**

*Method*
	POST

*Path Info*
	/

*Headers*
	Accept-Encoding: gzip,deflate
	User-Agent: Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.7.0_60)
	Cookie: $Version=1; sessionId="ce4923ec-a77a-480d-b73f-de9d665ee0fe"
	Connection: keep-alive
	Host: localhost:10101
	Content-Type: application/json; charset=UTF-8
	Content-Length: 691

*Query String*
	null

*Parameters*

*Body (First 100 characters only)*

Version 3.5 (everything set manually via header - also works)
**RESTClient TraceServlet**

*Method*
	POST

*Path Info*
	/

*Headers*
	Accept-Encoding: gzip,deflate
	User-Agent: Apache-HttpClient/4.4 (Java 1.5 minimum; Java/1.7.0_60)
	Cookie: sessionId=ce4923ec-a77a-480d-b73f-de9d665ee0fe; Version=1; Path=/
	Connection: keep-alive
	Host: localhost:10101
	Content-Type: application/json; charset=UTF-8
	Content-Length: 691

*Query String*
	null

*Parameters*

*Body (First 100 characters only)*

**Comment by subwiz** [comment] 2015-05-24 10:57
See the difference:

* 3.5: `Cookie: $Version=1; sessionId="ce4923ec-a77a-480d-b73f-de9d665ee0fe"`
* Custom: `Cookie: sessionId=ce4923ec-a77a-480d-b73f-de9d665ee0fe; Version=1; Path=/`

Can you try by setting the Cookie version to `v0`? To set the cookie version to `v0`, the option is in the `Etc.` tab.

**Comment by subwiz** [comment] 2015-05-26 16:15
I'm closing this as of now. If you are not satisfied with the resolution, please reopen.

**Closed by subwiz** 2015-05-26 16:15 UTC
